version: "3"
services:
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     - web
  #   restart: always
  #   environment:
  #     # STAGE: 'production'
  #     DOMAINS: 'walican.work => www.walican.work, www.walican.work -> http://web:8080'
  #     # FORCE_RENEW: 'true'
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
volumes:
  db: