version: "3"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
volumes:
  db: